var dict = Dictionary();


dict.put(\title, "GraphicalCollider");
dict.put(\userViewBackground, Color.gray(0.2));
dict.put(\menuFont, Font("Monaco", 16));
dict.put(\instBtnColor,
	Color(0.089887640449438, 0.65168539325843, 0.95505617977528
));
dict.put(\menuColor, Color.grey(0.7));
dict.put(\instListBackground, Color.grey(0.6));
dict.put(\newInstFont, Font("Monaco", 16));
dict.put(\mainWidth, 500);
dict.put(\mainHeight, 500);

dict;